[package]
name = "idm-cli"
version.workspace = true
description = "Query user details and assigned rights from an IdM (eDirectory) over LDAPS"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "idm"
path = "src/main.rs"

[dependencies]
ldap-cli-core.workspace = true
clap.workspace = true
tokio.workspace = true
ldap3.workspace = true
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
csv.workspace = true
comfy-table.workspace = true
console.workspace = true
chrono.workspace = true
